### ISSUE TITLE
DB & Models:  Define models, Create sequelize

### ISSUE THREAD

**Issue by ThomasCalle** [ThomasCalle/Project-2-Interactive-Full-Stack-Application#18]
Current goal is to complete database and models => push => review routes with Steve Cardie

**Comment by ThomasCalle** [comment]
# database 
- schema.sql 

 <Connected>

# models
- Category.js
- Event.js
- index.js
- User.js

// Datafields have been inputed //

**Comment by omgthegreenranger** [comment]
Database has been created based on models.
